import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
{/*import Link from 'next/link'*/}
import MenuIcon from '../../components/MenuIcon'
import MainMenu from '../../components/MainMenu'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ethan Matta Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <nav>
          <div className="menuContainer">
            <MenuIcon />
            <MainMenu />
          </div>
        </nav>
        <main className="flex-grow">
          {children}
        </main>
        <footer>
          <p>This is in the footer</p>
          <div className="return-to-top"></div>
        </footer>
      </body>
    </html>
  );
}